w = -10:0.01:10;

deln1 = [zeros(1,50) 1 zeros(1,50)];
N0 = 51;
X = DT_Fourier(deln1,N0,w);
figure;
subplot(2,2,1);
plot(w,abs(X));
xlabel("frequency");
ylabel("Magnitude");
subplot(2,2,2);
plot(w,angle(X));
xlabel("frequency");
ylabel("Phase");
subplot(2,2,3);
plot(w,real(X));
xlabel("frequency");
ylabel("Real Part");
subplot(2,2,4);
plot(w,imag(X));
xlabel("frequency");
ylabel("Imaginary Part");
sgtitle("unit impulse 𝛿[𝑛]");

deln2 = [zeros(1,50) 1 zeros(1,50)];
N1 = 54;
X1 = DT_Fourier(deln2,N1,w);
figure;
subplot(2,2,1);
plot(w,abs(X1));
xlabel("frequency");
ylabel("Magnitude");
subplot(2,2,2);
plot(w,angle(X1));
xlabel("frequency");
ylabel("Phase");
subplot(2,2,3);
plot(w,real(X1));
xlabel("frequency");
ylabel("Real Part");
subplot(2,2,4);
plot(w,imag(X1));
xlabel("frequency");
ylabel("Imaginary Part");
sgtitle("shifted unit impulse 𝛿[𝑛 + 3]");

rect = [zeros(1,47),1 1 1 1 1 1 1 zeros(1,47)];
N2 = 51;
X2 = DT_Fourier(rect,N2,w);
figure;
subplot(2,2,1);
plot(w,abs(X2));
xlabel("frequency");
ylabel("Magnitude");
subplot(2,2,2);
plot(w, angle(X2));
xlabel("frequency");
ylabel("Phase");
subplot(2,2,3);
plot(w,real(X2));
xlabel("frequency");
ylabel("Real Part");
subplot(2,2,4);
plot(w,imag(X2));
xlabel("frequency");
ylabel("Imaginary Part");
sgtitle("rectangular pulse from -3 to 3");

theta = -200:200;
sine = sin(pi/4*theta);
N3 = 201;
X3 = DT_Fourier(sine,N3,w);
figure;
subplot(2,2,1);
plot(w,abs(X3));
xlabel("frequency");
ylabel("Magnitude");
subplot(2,2,2);
plot(w,angle(X3));
xlabel("frequency");
ylabel("Phase");
subplot(2,2,3);
plot(w,real(X3));
xlabel("frequency");
ylabel("Real Part");
subplot(2,2,4);
plot(w,imag(X3));
xlabel("frequency");
ylabel("Imaginary Part");
sgtitle("finite duration sinusoid sin(𝜔0𝑛) with 𝜔0 =𝜋/4 for -200 to 200");